config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :games
  resources :orders
  # resources :users
  resources :genres
  resources :platforms

  root to: 'home#index'

  # get    'login'   => 'sessions#new'
  # get    'logout'  => 'sessions#destroy'
  # get    'signup'  => 'users#new'
  # get    'account' => 'users#show'
  get   'home'    => 'home#index'
  get   'search'  => 'search#index'
  get   'cart',   to: 'home#cart',   as: 'cart'
  # get   'orders', to: 'order#index', as: 'orders'

  post   'games/add_game_to_cart/:id',  to: 'games#add_game_to_cart', as: 'add_game_to_cart'
  post   'games/update_game_quantity/:id', to: 'games#update_game_quantity', as: 'update_game_quantity'
  delete 'games/remove_game_from_cart/:id', to: 'games#remove_game_from_cart', as: 'remove_game_from_cart'

  post   'platforms/add_platform_to_cart/:id', to: 'platforms#add_platform_to_cart', as: 'add_platform_to_cart'
  post   'platforms/update_platform_quantity/:id', to: 'platforms#update_platform_quantity', as: 'update_platform_quantity'
  delete 'platforms/remove_platform_from_cart/:id', to: 'platforms#remove_platform_from_cart', as: 'remove_platform_from_cart'

  # post 'home/update_quantity/:id', to: 'home#update_quantity', as: 'update_quantity_path'

  # post   'login'   => 'sessions#create' 
  # delete 'logout'  => 'sessions#destroy'

  devise_scope :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
    has_many :game_genres, dependent: :delete_all
    has_many :genres, through: :game_genres
    accepts_nested_attributes_for :game_genres, allow_destroy: true

    has_many :game_orders, dependent: :delete_all
    has_many :orders, through: :game_orders

    has_many :game_platforms, dependent: :delete_all
    has_many :platforms, through: :game_platforms
    accepts_nested_attributes_for :game_platforms, allow_destroy: true
    
    has_one_attached :image

    validates :name, :price, :description, presence: true
    validates :price, numericality: true
    def self.search(search)
        if search 
            where(["name LIKE ?","%#{search}%"])
        else
            all
        end
    end 
end

app/models/game_genre.rb
class GameGenre < ApplicationRecord
  belongs_to :game
  belongs_to :genre
end

app/models/game_order.rb
class GameOrder < ApplicationRecord
  belongs_to :game
  belongs_to :order
end

app/models/game_platform.rb
class GamePlatform < ApplicationRecord
  belongs_to :game
  belongs_to :platform
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :game_genres, dependent: :delete_all
    has_many :games, through: :game_genres

    validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :status
  belongs_to :user

  has_many :game_orders, dependent: :delete_all
  has_many :games, through: :game_orders
  accepts_nested_attributes_for :game_orders, allow_destroy: true

  has_many :platform_orders, dependent: :delete_all
  has_many :platforms, through: :platform_orders
  accepts_nested_attributes_for :platform_orders, allow_destroy: true
end

app/models/platform.rb
class Platform < ApplicationRecord
    has_many :game_platforms, dependent: :delete_all
    has_many :games, through: :game_platforms

    has_many :platform_orders, dependent: :delete_all
    has_many :Orders, through: :platform_orders

    has_one_attached :image

    validates :name, :price, :description, presence: true
    validates :price, numericality: true
end

app/models/platform_order.rb
class PlatformOrder < ApplicationRecord
  belongs_to :platform
  belongs_to :Order
end

app/models/province.rb
class Province < ApplicationRecord
    has_many :users
end

app/models/status.rb
class Status < ApplicationRecord
    has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :province
  has_many :orders
  accepts_nested_attributes_for :orders, allow_destroy: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
end

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController
  before_action :set_platform, only: %i[ show edit update destroy ]

  # GET /platforms or /platforms.json
  def index
    @filter = params[:filter]
    if(params[:filter] == "All" || params[:filter].nil?)
      @platforms = Platform.all.page(params[:page])
    elsif(params[:filter] == "Sale")
      @platforms = Platform.where.not(sale: nil).page(params[:page])
    elsif(params[:filter] == "Recent")
      @platforms = Platform.where(created_at: 3.days.ago..).page(params[:page])
    end
  end

  # GET /platforms/1 or /platforms/1.json
  def show
  end

  # GET /platforms/new
  def new
    @platform = Platform.new
  end

  # GET /platforms/1/edit
  def edit
  end

  # POST /platforms or /platforms.json
  def create
    @platform = Platform.new(platform_params)

    respond_to do |format|
      if @platform.save
        format.html { redirect_to platform_url(@platform), notice: "Platform was successfully created." }
        format.json { render :show, status: :created, location: @platform }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @platform.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /platforms/1 or /platforms/1.json
  def update
    respond_to do |format|
      if @platform.update(platform_params)
        format.html { redirect_to platform_url(@platform), notice: "Platform was successfully updated." }
        format.json { render :show, status: :ok, location: @platform }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @platform.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /platforms/1 or /platforms/1.json
  def destroy
    @platform.destroy

    respond_to do |format|
      format.html { redirect_to platforms_url, notice: "Platform was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_platform
      @platform = Platform.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def platform_params
      params.require(:platform).permit(:name, :description, :price)
    end
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:current_user_id] = user.id
  end
end

app/views/platforms/_form.html.erb
<%= form_with(model: platform) do |form| %>
  <% if platform.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(platform.errors.count, "error") %> prohibited this platform from being saved:</h2>

      <ul>
        <% platform.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/platforms/_platform.html.erb
<div class="column">
    <div class="card has-text-centered">
        <% if platform.image.present? %>
            <div class="card-image has-text-centered">
                <%= image_tag(platform.image, width: '200', alt: "#{platform.name} logo")%>
            </div>
        <% end %> 
        <div class="card-content">
            <p class="subtitle is-6 is-centered">
                <%= link_to platform.name, platform %>
            </p>                           
            <%if(platform.sale)%>
                    <p class="subtitle is-6 is-centered" >
                    <s style="color:red;"><%= number_to_currency(platform.price)%></s> | 
                    <span style="color:green;"><%=number_to_currency(platform.price - (platform.price * platform.sale))%></span>      
                    </p>              
                <%else%>
                    <p class="subtitle is-6 is-centered" style="color:green;"><%= number_to_currency(platform.price) %></p>     
                <%end%>
            <footer class="card-footer is-centered">                                
                <div class="card-footer-item">  
                    <%=button_to "Add to cart", add_platform_to_cart_path(platform.id), class: 'button is-primary'%>
                </div>   
            </footer>
        </div>
    </div>
</div>

app/views/platforms/edit.html.erb
<h1>Editing platform</h1>

<%= render "form", platform: @platform %>

<br>

<div>
  <%= link_to "Show this platform", @platform %> |
  <%= link_to "Back to platforms", platforms_path %>
</div>

app/views/platforms/index.html.erb
<p style="color: green"><%= notice %></p>
<%= form_with(url: '/platforms', method: 'get', local: true) do %>
  <select name="filter" id="filter">
    <option value="All">All</option>
    <option value="Sale">On Sale</option>
    <option value="Recent">Recently Added</option>
  </select>
  <%= submit_tag("Filter") %>
<% end %>

<h1 class="title is-2">Platforms</h1>
<%= paginate @platforms %>
<div class="columns is-multiline">
  <% @platforms.each do |p| %>
    <%= render partial: "platform", object: p %>
  <% end %>
</div>

<%= paginate @platforms %>

app/views/platforms/new.html.erb
<h1>New platform</h1>

<%= render "form", platform: @platform %>

<br>

<div>
  <%= link_to "Back to platforms", platforms_path %>
</div>

app/views/platforms/show.html.erb
<p style="color: green"><%= notice %></p>
<div id="game_platform" class="card has-text-centered">  
  <div class="card-content has-text-centered">
    <%= image_tag(@platform.image, :size => '200x200')%> 
    <div class="media-content">
      <p class="title is-4">
        <%= @platform.name %>
      </p> 
      <p>
        <%= @platform.description %>
      </p>
      <footer class="card-footer is-centered">
        <p class="card-footer-item"><%= number_to_currency(@platform.price) %></p>
        <div class="card-footer-item">  
          <%=button_to "Add to cart", add_platform_to_cart_path(@platform.id), class: 'button is-primary'%>
        <div>
      </footer>
    </div>        
  </div>

</div>  