config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :games
  resources :orders
  # resources :users
  resources :genres
  resources :platforms

  root to: 'home#index'

  # get    'login'   => 'sessions#new'
  # get    'logout'  => 'sessions#destroy'
  # get    'signup'  => 'users#new'
  # get    'account' => 'users#show'
  get   'home'    => 'home#index'
  get   'search'  => 'search#index'
  get   'cart',   to: 'home#cart',   as: 'cart'
  # get   'orders', to: 'order#index', as: 'orders'

  post   'games/add_game_to_cart/:id',  to: 'games#add_game_to_cart', as: 'add_game_to_cart'
  post   'games/update_game_quantity/:id', to: 'games#update_game_quantity', as: 'update_game_quantity'
  delete 'games/remove_game_from_cart/:id', to: 'games#remove_game_from_cart', as: 'remove_game_from_cart'

  post   'platforms/add_platform_to_cart/:id', to: 'platforms#add_platform_to_cart', as: 'add_platform_to_cart'
  post   'platforms/update_platform_quantity/:id', to: 'platforms#update_platform_quantity', as: 'update_platform_quantity'
  delete 'platforms/remove_platform_from_cart/:id', to: 'platforms#remove_platform_from_cart', as: 'remove_platform_from_cart'

  # post 'home/update_quantity/:id', to: 'home#update_quantity', as: 'update_quantity_path'

  # post   'login'   => 'sessions#create' 
  # delete 'logout'  => 'sessions#destroy'

  devise_scope :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
    has_many :game_genres, dependent: :delete_all
    has_many :genres, through: :game_genres
    accepts_nested_attributes_for :game_genres, allow_destroy: true

    has_many :game_orders, dependent: :delete_all
    has_many :orders, through: :game_orders

    has_many :game_platforms, dependent: :delete_all
    has_many :platforms, through: :game_platforms
    accepts_nested_attributes_for :game_platforms, allow_destroy: true
    
    has_one_attached :image

    validates :name, :price, :description, presence: true
    validates :price, numericality: true
    def self.search(search)
        if search 
            where(["name LIKE ?","%#{search}%"])
        else
            all
        end
    end 
end

app/models/game_genre.rb
class GameGenre < ApplicationRecord
  belongs_to :game
  belongs_to :genre
end

app/models/game_order.rb
class GameOrder < ApplicationRecord
  belongs_to :game
  belongs_to :order
end

app/models/game_platform.rb
class GamePlatform < ApplicationRecord
  belongs_to :game
  belongs_to :platform
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :game_genres, dependent: :delete_all
    has_many :games, through: :game_genres

    validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :status
  belongs_to :user

  has_many :game_orders, dependent: :delete_all
  has_many :games, through: :game_orders
  accepts_nested_attributes_for :game_orders, allow_destroy: true

  has_many :platform_orders, dependent: :delete_all
  has_many :platforms, through: :platform_orders
  accepts_nested_attributes_for :platform_orders, allow_destroy: true
end

app/models/platform.rb
class Platform < ApplicationRecord
    has_many :game_platforms, dependent: :delete_all
    has_many :games, through: :game_platforms

    has_many :platform_orders, dependent: :delete_all
    has_many :Orders, through: :platform_orders

    has_one_attached :image

    validates :name, :price, :description, presence: true
    validates :price, numericality: true
end

app/models/platform_order.rb
class PlatformOrder < ApplicationRecord
  belongs_to :platform
  belongs_to :Order
end

app/models/province.rb
class Province < ApplicationRecord
    has_many :users
end

app/models/status.rb
class Status < ApplicationRecord
    has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :province
  has_many :orders
  accepts_nested_attributes_for :orders, allow_destroy: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @games = Game.order(created_at: :desc).limit(21)
    @platforms = Platform.limit(15)
  end
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:current_user_id] = user.id
  end
end

app/views/home/cart.html.erb
<h1 class="title is-2">Your Cart</h1>

<%if @cart.empty?%>
    <p>Cart is empty.</p>
<%else%>
    <table class="table is-fullwidth is-bordered text-is-centered">
        <thead>
            <tr>
                <th>Image</th>
                <th>Name</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Total</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <%@cart.each do |product|%>
                <tr>
                    <td><%= image_tag(product.image, width: '100', alt: "#{product.name.truncate(10)}")%></td>
                    <td class="has-text-justified has-text-centered"><%= link_to product.name.truncate(50), product %></td>
                    <td class="has-text-justified has-text-centered">
                    <%if(product.sale)%>
                            <%=number_to_currency((product.price - (product.price * product.sale)))%>
                        <%else%>
                            <%=number_to_currency(product.price)%>
                        <%end%>
                    </td>                   
                    <%if(product.is_a? Game)%>
                        <td class="has-text-justified has-text-centered">
                            <%= form_with(url: update_game_quantity_path(product.id.to_s), method: :post, local: true) do %>                            
                                <select name="quantity">
                                    <% for v in 1..10 do%>
                                        <%if v == session[:cart_games][product.id.to_s] %>
                                            <option value="<%=v%>" selected="selected"><%=v%></option>
                                        <%else%>
                                            <option value="<%=v%>"><%=v%></option>
                                        <%end%>
                                    <%end%>
                                </select>
                                <input type="hidden" name="id" value="<%=product.id.to_s%>"/>
                                <button class="button is-confirm" type="submit">Update</button>                            
                            <%end%>
                        </td>
                        <%if(product.sale)%>
                            <td><%=number_to_currency((product.price - (product.price * product.sale))* session[:cart_games][product.id.to_s])%></td>
                        <%else%>
                            <td><%=number_to_currency(product.price * session[:cart_games][product.id.to_s])%></td>
                        <%end%>
                    <%else%>
                        <td class="has-text-justified has-text-centered">
                            <%= form_with(url: update_platform_quantity_path(product.id.to_s), method: :post, local: true) do %>                            
                                <select name="quantity">
                                    <% for v in 1..10 do%>
                                        <%if v == session[:cart_platforms][product.id.to_s] %>
                                            <option value="<%=v%>" selected="selected"><%=v%></option>
                                        <%else%>
                                            <option value="<%=v%>"><%=v%></option>
                                        <%end%>
                                    <%end%>
                                </select>
                                <input type="hidden" name="id" value="<%=product.id.to_s%>"/>
                                <button class="button is-confirm" type="submit">Update</button>                            
                            <%end%>
                        </td>
                        <td><%=number_to_currency(product.price * session[:cart_platforms][product.id.to_s])%></td>
                    <%end%>                   
                    <%if(product.is_a? Game)%>
                        <td><%=button_to "Remove", remove_game_from_cart_path(product.id.to_s), method: :delete, class: "button is-small is-danger"%></td>
                    <%else%>
                        <td><%=button_to "Remove", remove_platform_from_cart_path(product.id.to_s), method: :delete, class: "button is-small is-danger"%></td>
                    <%end%>
                </tr>
            <%end%>
            <tr>
                <td></td>
                <td></td>
                <td></td>                
                <td>Subtotal</td>
                <td><%=number_to_currency(@sub)%></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>                
                <td>Taxes</td>
                <%if(@tax <= 0)%>
                    <td>Calculated at Check Out</td>
                <%else%>
                    <td><%=number_to_currency(@tax)%></td>
                <%end%>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>                
                <td>Total</td>
                <td><%=number_to_currency(@total)%></td>
                <td>
                    <%if(user_signed_in?)%>
                        <%=button_to "Checkout", checkout_create_path, method: :post, class: "button is-primary", params: {subtotal: @sub, tax: @tax, total: @total}%>
                    <%else%>
                        <%=button_to "Sign In to Checkout", new_user_session_path, class: "button is-primary", method: :get%>
                    <%end%>
                </td>
            </tr>
        </tbody>
    </table>
<%end%>

app/views/home/index.html.erb
<h1 class="title is-2">Home</h1>

<h2 class="title is-3">Recently Added</h2>
<div id="home" class="columns is-multiline">    
    <% @games.each do |g| %>
        <div class="column">
            <%= render partial: "games/game", object: g %>    
        </div>
    <% end %>
</div>