config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :games
  resources :orders
  # resources :users
  resources :genres
  resources :platforms

  root to: 'home#index'

  # get    'login'   => 'sessions#new'
  # get    'logout'  => 'sessions#destroy'
  # get    'signup'  => 'users#new'
  # get    'account' => 'users#show'
  get   'home'    => 'home#index'
  get   'search'  => 'search#index'
  get   'cart',   to: 'home#cart',   as: 'cart'
  # get   'orders', to: 'order#index', as: 'orders'

  post   'games/add_game_to_cart/:id',  to: 'games#add_game_to_cart', as: 'add_game_to_cart'
  post   'games/update_game_quantity/:id', to: 'games#update_game_quantity', as: 'update_game_quantity'
  delete 'games/remove_game_from_cart/:id', to: 'games#remove_game_from_cart', as: 'remove_game_from_cart'

  post   'platforms/add_platform_to_cart/:id', to: 'platforms#add_platform_to_cart', as: 'add_platform_to_cart'
  post   'platforms/update_platform_quantity/:id', to: 'platforms#update_platform_quantity', as: 'update_platform_quantity'
  delete 'platforms/remove_platform_from_cart/:id', to: 'platforms#remove_platform_from_cart', as: 'remove_platform_from_cart'

  # post 'home/update_quantity/:id', to: 'home#update_quantity', as: 'update_quantity_path'

  # post   'login'   => 'sessions#create' 
  # delete 'logout'  => 'sessions#destroy'

  devise_scope :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
    has_many :game_genres, dependent: :delete_all
    has_many :genres, through: :game_genres
    accepts_nested_attributes_for :game_genres, allow_destroy: true

    has_many :game_orders, dependent: :delete_all
    has_many :orders, through: :game_orders

    has_many :game_platforms, dependent: :delete_all
    has_many :platforms, through: :game_platforms
    accepts_nested_attributes_for :game_platforms, allow_destroy: true
    
    has_one_attached :image

    validates :name, :price, :description, presence: true
    validates :price, numericality: true
    def self.search(search)
        if search 
            where(["name LIKE ?","%#{search}%"])
        else
            all
        end
    end 
end

app/models/game_genre.rb
class GameGenre < ApplicationRecord
  belongs_to :game
  belongs_to :genre
end

app/models/game_order.rb
class GameOrder < ApplicationRecord
  belongs_to :game
  belongs_to :order
end

app/models/game_platform.rb
class GamePlatform < ApplicationRecord
  belongs_to :game
  belongs_to :platform
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :game_genres, dependent: :delete_all
    has_many :games, through: :game_genres

    validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :status
  belongs_to :user

  has_many :game_orders, dependent: :delete_all
  has_many :games, through: :game_orders
  accepts_nested_attributes_for :game_orders, allow_destroy: true

  has_many :platform_orders, dependent: :delete_all
  has_many :platforms, through: :platform_orders
  accepts_nested_attributes_for :platform_orders, allow_destroy: true
end

app/models/platform.rb
class Platform < ApplicationRecord
    has_many :game_platforms, dependent: :delete_all
    has_many :games, through: :game_platforms

    has_many :platform_orders, dependent: :delete_all
    has_many :Orders, through: :platform_orders

    has_one_attached :image

    validates :name, :price, :description, presence: true
    validates :price, numericality: true
end

app/models/platform_order.rb
class PlatformOrder < ApplicationRecord
  belongs_to :platform
  belongs_to :Order
end

app/models/province.rb
class Province < ApplicationRecord
    has_many :users
end

app/models/status.rb
class Status < ApplicationRecord
    has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :province
  has_many :orders
  accepts_nested_attributes_for :orders, allow_destroy: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]
  
  # GET /games or /games.json
  def index
    if(params[:filter] == "All" || params[:filter].nil?)
      @games = Game.search(params[:search]).page(params[:page])
      @filter = params[:filter]
    elsif(params[:filter] == "Sale")
      @games = Game.where.not(sale: nil).page(params[:page])
      @filter = params[:filter]
    elsif(params[:filter] == "Recent")
      @games = Game.where(created_at: 3.days.ago..).order('created_at DESC').page(params[:page])
      @filter = params[:filter]
    end
  end

  # GET /games/1 or /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games or /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to game_url(@game), notice: "Game was successfully created." }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to game_url(@game), notice: "Game was successfully updated." }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url, notice: "Game was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_params
      params.fetch(:game, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:current_user_id] = user.id
  end
end

app/views/games/_form.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/games/_game.html.erb
<div class="column">
    <div class="card has-text-centered">               
        <% if game.image.present? %>
            <div class="card-image has-text-centered">
                <%= image_tag(game.image, width: '200', alt: "#{game.name.truncate(10)} cover")%>
            </div>
        <% end %>        
        <div class="card-content">            
            <p class="title is-5 is-centered">
                <%= link_to game.name.truncate(15), game %>
            </p>
                <%if(game.sale)%>
                    <p class="subtitle is-6 is-centered" >
                    <s style="color:red;"><%= number_to_currency(game.price)%></s> | 
                    <span style="color:green;"><%=number_to_currency(game.price - (game.price * game.sale))%></span>      
                    </p>              
                <%else%>
                    <p class="subtitle is-6 is-centered" style="color:green;"><%= number_to_currency(game.price) %></p>     
                <%end%>
            <footer class="card-footer is-centered">                
                <div class="card-footer-item">  
                    <%=button_to "Add to cart", add_game_to_cart_path(game.id), class: 'button is-primary'%>
                </div>       
            </footer>
        </div>
    </div>
</div>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Show this game", @game %> |
  <%= link_to "Back to games", games_path %>
</div>

app/views/games/index.html.erb
<p style="color: green"><%= notice %></p>

<%= form_with(url: '/games', method: 'get', local: true) do %>
  <select name="filter" id="filter">
    <option value="All">All</option>
    <option value="Sale">On Sale</option>
    <option value="Recent">Recently Added</option>
  </select>
  <%= submit_tag("Filter") %>
<% end %>

<h1 class="title is-2">Games</h1>
<%= paginate @games %>

<div class="columns is-multiline">
  <% @games.each do |g| %>
    <%= render partial: "game", object: g %>    
  <% end %>
</div>

<%= paginate @games %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Back to games", games_path %>
</div>

app/views/games/show.html.erb
<p style="color: green"><%= notice %></p>

<div id="game_platform" class="card">  
  <% if @game.image.present? %>
    <div class="card-image has-text-centered">
      <%= image_tag(@game.image, width: '200')%>
    </div>
  <% end %>   
  <div class="card-content">     
    <div class="media-content">
      <p class="title is-4">
        <%= @game.name %>
      </p> 
      <p>
        <%= @game.description %>
      </p>
      <p class="card-footer-item">
        <b>Genres:&nbsp </b>
        <%@game.genres.each do |genre|%>
          <%= genre.name %> |
        <%end%>
      </p>
      <p class="card-footer-item">
        <b>Platforms:&nbsp </b>
        <%@game.platforms.each do |platform|%>
          <%= platform.name %> |
        <%end%>
      </p>
      <% if @game.age_rating.present? %>          
            <p class="card-footer-item">
              <b>ESRB Rating:&nbsp </b> <%= @game.age_rating %>
            </p>                     
        <% end %>  
      <footer class="card-footer has-text-centered"> 
        <div class="card-footer-item">  
          <%=button_to "Add to cart", add_game_to_cart_path(@game.id), class: 'button is-primary'%>
        <div>       
    </div>        
  </div>
</div>  