config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :games
  resources :orders
  # resources :users
  resources :genres
  resources :platforms

  root to: 'home#index'

  # get    'login'   => 'sessions#new'
  # get    'logout'  => 'sessions#destroy'
  # get    'signup'  => 'users#new'
  # get    'account' => 'users#show'
  get   'home'    => 'home#index'
  get   'search'  => 'search#index'
  get   'cart',   to: 'home#cart',   as: 'cart'
  # get   'orders', to: 'order#index', as: 'orders'

  post   'games/add_game_to_cart/:id',  to: 'games#add_game_to_cart', as: 'add_game_to_cart'
  post   'games/update_game_quantity/:id', to: 'games#update_game_quantity', as: 'update_game_quantity'
  delete 'games/remove_game_from_cart/:id', to: 'games#remove_game_from_cart', as: 'remove_game_from_cart'

  post   'platforms/add_platform_to_cart/:id', to: 'platforms#add_platform_to_cart', as: 'add_platform_to_cart'
  post   'platforms/update_platform_quantity/:id', to: 'platforms#update_platform_quantity', as: 'update_platform_quantity'
  delete 'platforms/remove_platform_from_cart/:id', to: 'platforms#remove_platform_from_cart', as: 'remove_platform_from_cart'

  # post 'home/update_quantity/:id', to: 'home#update_quantity', as: 'update_quantity_path'

  # post   'login'   => 'sessions#create' 
  # delete 'logout'  => 'sessions#destroy'

  devise_scope :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/game.rb
class Game < ApplicationRecord
    has_many :game_genres, dependent: :delete_all
    has_many :genres, through: :game_genres
    accepts_nested_attributes_for :game_genres, allow_destroy: true

    has_many :game_orders, dependent: :delete_all
    has_many :orders, through: :game_orders

    has_many :game_platforms, dependent: :delete_all
    has_many :platforms, through: :game_platforms
    accepts_nested_attributes_for :game_platforms, allow_destroy: true
    
    has_one_attached :image

    validates :name, :price, :description, presence: true
    validates :price, numericality: true
    def self.search(search)
        if search 
            where(["name LIKE ?","%#{search}%"])
        else
            all
        end
    end 
end

app/models/game_genre.rb
class GameGenre < ApplicationRecord
  belongs_to :game
  belongs_to :genre
end

app/models/game_order.rb
class GameOrder < ApplicationRecord
  belongs_to :game
  belongs_to :order
end

app/models/game_platform.rb
class GamePlatform < ApplicationRecord
  belongs_to :game
  belongs_to :platform
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :game_genres, dependent: :delete_all
    has_many :games, through: :game_genres

    validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :status
  belongs_to :user

  has_many :game_orders, dependent: :delete_all
  has_many :games, through: :game_orders
  accepts_nested_attributes_for :game_orders, allow_destroy: true

  has_many :platform_orders, dependent: :delete_all
  has_many :platforms, through: :platform_orders
  accepts_nested_attributes_for :platform_orders, allow_destroy: true
end

app/models/platform.rb
class Platform < ApplicationRecord
    has_many :game_platforms, dependent: :delete_all
    has_many :games, through: :game_platforms

    has_many :platform_orders, dependent: :delete_all
    has_many :Orders, through: :platform_orders

    has_one_attached :image

    validates :name, :price, :description, presence: true
    validates :price, numericality: true
end

app/models/platform_order.rb
class PlatformOrder < ApplicationRecord
  belongs_to :platform
  belongs_to :Order
end

app/models/province.rb
class Province < ApplicationRecord
    has_many :users
end

app/models/status.rb
class Status < ApplicationRecord
    has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :province
  has_many :orders
  accepts_nested_attributes_for :orders, allow_destroy: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:current_user_id] = user.id
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>GameShack</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar is-dark" aria-label="main navigation">
      <div class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item" href=<%=home_path%>>
            Home
          </a>
          <a class="navbar-item" href=<%=games_path%>>
            Games
          </a>
          <a class="navbar-item" href=<%=platforms_path%>>
            Platforms
          </a> 
          <a class="navbar-item" href=<%=genres_path%>>
            Genres
          </a>     
          <div class="navbar-item"> 
            <%= form_with(url: '/search', method: 'get', local: true) do %>
              <%= text_field_tag(:search) %>
              <select name="platforms" id="platforms">
                  <option value="All">All Platforms</option>
                <% Platform.all.each do |p|%>
                  <option value="<%=p.id%>"><%=p.name%></option>
                <%end%>
              </select>
              <%= submit_tag("Search") %>
            <% end %>
          </div>
        </div>
        <div class="navbar-end">          
          <div class="navbar-item">
            <%=button_to "Admin", admin_root_path, class: "button is-danger", method: :get%>&nbsp;
            <%if user_signed_in?%>
              <%=button_to "Account", edit_user_registration_path, class: "button is-primary", method: :get%>&nbsp;
              <%=button_to "Sign Out", destroy_user_session_path, class: "button is-danger", method: :get%>
            <%else%>
              <%=button_to "Sign Up", new_user_registration_path, class: "button is-primary", method: :get%>&nbsp;
              <%=button_to "Sign In", new_user_session_path, class: "button is-primary", method: :get%>
            <%end%>
            <p>&nbsp;|&nbsp;</p>
            <%if(@cart_count != 0)%>
              <%=link_to "Cart (#{@cart_count})", cart_path, class: "button is-primary", method: :get%>
            <%else%>
              <%=link_to "Cart", cart_path, class: "button is-primary", method: :get%>
            <%end%>
          </div>
        </div>
      </div>
    </nav>
    <p class = "notice"><%=notice%></p>
    <p class = "alert"><%=alert%></p>
    <%= yield %>
  </body>
</html>